### ISSUE TITLE
Convertion bytea to image is killing PID Postgres

### ISSUE THREAD

**Issue by bemanuel** [drotiro/postpic#4]
Using Postgres 9.2 and 9.3.x. graphicsmagick 1.3.18. Ubuntu 13.10/14.04 amd64.
How can i debug on Postpic?

select image_from_bytea(img_ba) from images limit 2;
0.0.1(46651) SELECT: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
A conexão com servidor foi perdida. Tentando reiniciar: LOG:  server process (PID 10496) was terminated by signal 6: Aborted
DETAIL:  Failed process was running: select image_from_bytea(img_ba) from images limit 2;
LOG:  terminating any other active server processes

---------------------------------------------------------------------------------------------
Other situation:
2014-05-06 14:09:38 BRT LOG:  processo servidor (PID 3072) foi terminado pelo sinal 11: Segmentation fault
2014-05-06 14:09:38 BRT DETALHE:  Processo que falhou estava executando: select thumbnail(the_img,15) from images;

---------------------------------------------------------------------------------------------

**Comment by drotiro** [comment]
Hi @bemanuel, 
have you had any chance to do some debug?

I tried with a CentOS 6.4 x86_64 and all went fine:

    postgres=# update tabela_tempo_image_problema SET noti_imagem_base = image_from_bytea(noti_imagem);        
    UPDATE 9                                                                                                   

and

    postgres=# select width(noti_imagem_base), height(noti_imagem_base), noti_id, noti_titulo from tabela_tempo_image_problema;
     width | height | noti_id |                                  noti_titulo
    -------+--------+---------+-------------------------------------------------------------------------------
       768 |    576 |       2 | Agespisa investe mais de R$ 254 milhÃµes no interior
      1600 |   1059 |       8 | Agespisa perfura poÃ§o para atender comunidades da zona leste de THE
       768 |    512 |     189 | Agespisa avanÃ§a em obra de esgotamento sanitÃ¡rio em Amarante
       768 |    576 |     191 | Governador inaugura sistema de abastecimento em Campo Grande
       768 |    552 |     194 | Agespisa instala equipamentos em novos poÃ§os na zona Sul
       768 |    559 |     198 | Presidente da Agespisa se reÃºne com prefeito Firmino Filho
       699 |    492 |     208 | Agespisa apresenta proposta para implantar esgoto na zona Sudeste de Teresina
      1600 |   1200 |     209 | Novos diretores da Agespisa sÃ£o empossados
      2144 |   1424 |     211 | Servidores da Agespisa participam de palestra com Amyr Klink
    (9 rows)

Also resize worked fine.
Please let me know if you still have problems, otherwise I'll close the issue.
Regards.
