### ISSUE TITLE
couldn't compile on my osx system

### ISSUE THREAD

**Issue by u32744** [drotiro/postpic#7]
I had compiled Postgresql and GraphicsMagick, when I run make in the postpic source folder,
the console shows this information:
ld: library not found for -lGraphicsMagick
clang: error: linker command failed with exit code 1(use -v to see invocation)

**Comment by drotiro** [comment]
Hi,
it seems that you're using clang, please be aware that I only tested compilation with gcc on Linux .

Anyway, the linker complains that libGraphicsMagick.so is not in your library path.
Find the directory containing the library (/usr/lib64 in my case) and add it to LD_LIBRARY_PATH env variable or to the ld configuration file (for me is /etc/ld.so.conf)

Regards,
Domenico

**Comment by u32744** [comment]
Thank you for your replay, I'm set LD_LIBRARY_PATH to my graphicsmagick lib path and recompile,but a new problem:ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [postpic.so] Error 1
make: *** [postpic] Error 1 I don't know why. my system is MAC OSX 10.9Thank you very much.----- 原文 ----- 发件人: Domenico Rotiroti 主　题: Re: [postpic] couldn't compile on my osx system (#7)时　间: 2015年4月1日  GMT+8下午4:27:02抄　送: u32744, &nbsp;Hi,
it seems that you're using clang, please be aware that I only tested compilation with gcc on Linux .

Anyway, the linker complains that libGraphicsMagick.so is not in your library path.
Find the directory containing the library (/usr/lib64 in my case) and add it to LD_LIBRARY_PATH env variable or to the ld configuration file (for me is /etc/ld.so.conf)

Regards,
Domenico

**Comment by u32744** [comment]
gcc postpic.c -fPIC -I"/usr/local/PostgreSql/include" -I"/usr/local/graphicsmagick/include/GraphicsMagick" -shared -o postpic.so $(GraphicsMagick-config --libs)
Undefined symbols for architecture x86_64:
&nbsp; "_DatumGetFloat4", referenced from:
&nbsp; &nbsp; &nbsp; _image_rotate in postpic-a2e4a5.o
&nbsp; "_DirectFunctionCall1Coll", referenced from:
&nbsp; &nbsp; &nbsp; _image_in in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_out in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_recv in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _lo_size in postpic-a2e4a5.o
&nbsp; "_DirectFunctionCall2Coll", referenced from:
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp; "_DirectFunctionCall3Coll", referenced from:
&nbsp; &nbsp; &nbsp; _lo_size in postpic-a2e4a5.o
&nbsp; "_Float4GetDatum", referenced from:
&nbsp; &nbsp; &nbsp; _image_f_number in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_exposure_time in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_focal_length in postpic-a2e4a5.o
&nbsp; "_GetSysCacheOid", referenced from:
&nbsp; &nbsp; &nbsp; __PG_init in postpic-a2e4a5.o
&nbsp; "_byteain", referenced from:
&nbsp; &nbsp; &nbsp; _image_in in postpic-a2e4a5.o
&nbsp; "_byteaout", referenced from:
&nbsp; &nbsp; &nbsp; _image_out in postpic-a2e4a5.o
&nbsp; "_bytearecv", referenced from:
&nbsp; &nbsp; &nbsp; _image_recv in postpic-a2e4a5.o
&nbsp; "_elog_finish", referenced from:
&nbsp; &nbsp; &nbsp; _image_new in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_index in postpic-a2e4a5.o
&nbsp; "_elog_start", referenced from:
&nbsp; &nbsp; &nbsp; _image_new in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_index in postpic-a2e4a5.o
&nbsp; "_errcode", referenced from:
&nbsp; &nbsp; &nbsp; _gm_image_from_bytea in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp; "_errfinish", referenced from:
&nbsp; &nbsp; &nbsp; _gm_image_from_bytea in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp; "_errmsg", referenced from:
&nbsp; &nbsp; &nbsp; _gm_image_from_bytea in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp; "_errstart", referenced from:
&nbsp; &nbsp; &nbsp; _gm_image_from_bytea in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp; "_lo_close", referenced from:
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp; "_lo_lseek", referenced from:
&nbsp; &nbsp; &nbsp; _lo_size in postpic-a2e4a5.o
&nbsp; "_lo_open", referenced from:
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp; "_lo_read", referenced from:
&nbsp; &nbsp; &nbsp; _lo_readblob in postpic-a2e4a5.o
&nbsp;&nbsp; &nbsp; (maybe you meant: _lo_readblob)
&nbsp; "_lo_tell", referenced from:
&nbsp; &nbsp; &nbsp; _lo_size in postpic-a2e4a5.o
&nbsp; "_palloc", referenced from:
&nbsp; &nbsp; &nbsp; _pp_init_image_full in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _color_in in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _color_out in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _pp_varchar2str in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _gm_ppacket_from_color in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_index in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _postpic_version in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; ...
&nbsp; "_pg_atoi", referenced from:
&nbsp; &nbsp; &nbsp; _pp_parse_int in postpic-a2e4a5.o
&nbsp; "_pg_detoast_datum", referenced from:
&nbsp; &nbsp; &nbsp; _image_out in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_from_bytea in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_send in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_thumbnail in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_resize in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_crop in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _image_rotate in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; ...
&nbsp; "_pstrdup", referenced from:
&nbsp; &nbsp; &nbsp; _image_index in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _gm_image_getattr in postpic-a2e4a5.o
&nbsp; &nbsp; &nbsp; _pp_str2timestamp in postpic-a2e4a5.o
&nbsp; "_tm2timestamp", referenced from:
&nbsp; &nbsp; &nbsp; _pp_str2timestamp in postpic-a2e4a5.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) ----- 原文 ----- 发件人: Domenico Rotiroti 主　题: Re: [postpic] couldn't compile on my osx system (#7)时　间: 2015年4月1日  GMT+8下午4:27:02抄　送: u32744, &nbsp;Hi,
it seems that you're using clang, please be aware that I only tested compilation with gcc on Linux .

Anyway, the linker complains that libGraphicsMagick.so is not in your library path.
Find the directory containing the library (/usr/lib64 in my case) and add it to LD_LIBRARY_PATH env variable or to the ld configuration file (for me is /etc/ld.so.conf)

Regards,
Domenico

**Comment by drotiro** [comment]
Hi,
it seems that you are compiling for x86_64 and have a 32-bit Postgres.

Please check that all the code you're about to link is for the same architecture.

Regarards,
Domenico

**Comment by u32744** [comment]
could you help me to change to 64-bit source? because my cpu not 32 bit. thank you!----- 原文 ----- 发件人: Domenico Rotiroti 主　题: Re: [postpic] couldn't compile on my osx system (#7)时　间: 2015年4月27日  GMT+8下午10:35:39抄　送: u32744,  Hi,
it seems that you are compiling for x86_64 and have a 32-bit Postgres.

Please check that all the code you're about to link is for the same architecture.

Regarards,
Domenico
