### ISSUE TITLE
Compiling with Windows

### ISSUE THREAD

**Issue by homer90** [drotiro/postpic#9]
Hello,

 i installed PostgreSQL on Windows and would like to use your extension as it sounds very promising.

I read that you would need Visual Studio to compile a Postgres extension with windows. However i do not own a licence for VS.

Is there any other way i could get it work with windows?

Thanks.

**Comment by drotiro** [comment]
Hi,
I haven't done any test on windows.
You can try to build with MinGW, as explained [here](https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules#Windows_with_MinGW).

Regards,
Domenico.
